module Autorender
  module Models
    type file_rename_params =
      { file_no: String, name: String }
      & Autorender::Internal::Type::request_parameters

    class FileRenameParams < Autorender::Internal::Type::BaseModel
      extend Autorender::Internal::Type::RequestParameters::Converter
      include Autorender::Internal::Type::RequestParameters

      attr_accessor file_no: String

      attr_accessor name: String

      def initialize: (
        file_no: String,
        name: String,
        ?request_options: Autorender::request_opts
      ) -> void

      def to_hash: -> {
        file_no: String,
        name: String,
        request_options: Autorender::RequestOptions
      }
    end
  end
end
