module Autorender
  module Models
    type file_update_response =
      {
        data: Autorender::Models::FileUpdateResponse::Data,
        success: Autorender::Models::FileUpdateResponse::success
      }

    class FileUpdateResponse < Autorender::Internal::Type::BaseModel
      attr_accessor data: Autorender::Models::FileUpdateResponse::Data

      attr_accessor success: Autorender::Models::FileUpdateResponse::success

      def initialize: (
        data: Autorender::Models::FileUpdateResponse::Data,
        success: Autorender::Models::FileUpdateResponse::success
      ) -> void

      def to_hash: -> {
        data: Autorender::Models::FileUpdateResponse::Data,
        success: Autorender::Models::FileUpdateResponse::success
      }

      type data =
        {
          id: String,
          created_at: Time,
          file_no: String,
          folder_name: String?,
          folder_no: String?,
          format_: String?,
          height: Integer?,
          metadata: ::Hash[Symbol, top]?,
          mime_type: String,
          name: String,
          path: String,
          size: Integer,
          source: String,
          tags: ::Array[String],
          updated_at: Time?,
          url: String,
          width: Integer?
        }

      class Data < Autorender::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor file_no: String

        attr_accessor folder_name: String?

        attr_accessor folder_no: String?

        attr_accessor format_: String?

        attr_accessor height: Integer?

        attr_accessor metadata: ::Hash[Symbol, top]?

        attr_accessor mime_type: String

        attr_accessor name: String

        attr_accessor path: String

        attr_accessor size: Integer

        attr_accessor source: String

        attr_accessor tags: ::Array[String]

        attr_accessor updated_at: Time?

        attr_accessor url: String

        attr_accessor width: Integer?

        def initialize: (
          id: String,
          created_at: Time,
          file_no: String,
          folder_name: String?,
          folder_no: String?,
          format_: String?,
          height: Integer?,
          metadata: ::Hash[Symbol, top]?,
          mime_type: String,
          name: String,
          path: String,
          size: Integer,
          source: String,
          tags: ::Array[String],
          updated_at: Time?,
          url: String,
          width: Integer?
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          file_no: String,
          folder_name: String?,
          folder_no: String?,
          format_: String?,
          height: Integer?,
          metadata: ::Hash[Symbol, top]?,
          mime_type: String,
          name: String,
          path: String,
          size: Integer,
          source: String,
          tags: ::Array[String],
          updated_at: Time?,
          url: String,
          width: Integer?
        }
      end

      type success = true

      module Success
        extend Autorender::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[Autorender::Models::FileUpdateResponse::success]
      end
    end
  end
end
