module Autorender
  module Models
    type file_list_params =
      {
        folder_no: String,
        limit: Integer,
        name: String,
        page: Integer,
        path: String,
        sort: Autorender::Models::FileListParams::sort,
        tags: String
      }
      & Autorender::Internal::Type::request_parameters

    class FileListParams < Autorender::Internal::Type::BaseModel
      extend Autorender::Internal::Type::RequestParameters::Converter
      include Autorender::Internal::Type::RequestParameters

      attr_reader folder_no: String?

      def folder_no=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader page: Integer?

      def page=: (Integer) -> Integer

      attr_reader path: String?

      def path=: (String) -> String

      attr_reader sort: Autorender::Models::FileListParams::sort?

      def sort=: (
        Autorender::Models::FileListParams::sort
      ) -> Autorender::Models::FileListParams::sort

      attr_reader tags: String?

      def tags=: (String) -> String

      def initialize: (
        ?folder_no: String,
        ?limit: Integer,
        ?name: String,
        ?page: Integer,
        ?path: String,
        ?sort: Autorender::Models::FileListParams::sort,
        ?tags: String,
        ?request_options: Autorender::request_opts
      ) -> void

      def to_hash: -> {
        folder_no: String,
        limit: Integer,
        name: String,
        page: Integer,
        path: String,
        sort: Autorender::Models::FileListParams::sort,
        tags: String,
        request_options: Autorender::RequestOptions
      }

      type sort = :created_at_asc | :created_at_desc | :size_asc | :size_desc

      module Sort
        extend Autorender::Internal::Type::Enum

        CREATED_AT_ASC: :created_at_asc
        CREATED_AT_DESC: :created_at_desc
        SIZE_ASC: :size_asc
        SIZE_DESC: :size_desc

        def self?.values: -> ::Array[Autorender::Models::FileListParams::sort]
      end
    end
  end
end
