module Autorender
  module Models
    type folder_create_params =
      { folder_name: String, path: String }
      & Autorender::Internal::Type::request_parameters

    class FolderCreateParams < Autorender::Internal::Type::BaseModel
      extend Autorender::Internal::Type::RequestParameters::Converter
      include Autorender::Internal::Type::RequestParameters

      attr_accessor folder_name: String

      attr_reader path: String?

      def path=: (String) -> String

      def initialize: (
        folder_name: String,
        ?path: String,
        ?request_options: Autorender::request_opts
      ) -> void

      def to_hash: -> {
        folder_name: String,
        path: String,
        request_options: Autorender::RequestOptions
      }
    end
  end
end
