module Autorender
  module Models
    type folder_list_response = { folders: ::Array[Autorender::FolderListItem] }

    class FolderListResponse < Autorender::Internal::Type::BaseModel
      attr_reader folders: ::Array[Autorender::FolderListItem]?

      def folders=: (
        ::Array[Autorender::FolderListItem]
      ) -> ::Array[Autorender::FolderListItem]

      def initialize: (?folders: ::Array[Autorender::FolderListItem]) -> void

      def to_hash: -> { folders: ::Array[Autorender::FolderListItem] }
    end
  end
end
