module Autorender
  module Models
    type folder_list_item =
      {
        created_at: Time,
        folder_no: String,
        name: String,
        total_items: Integer,
        total_size: Integer
      }

    class FolderListItem < Autorender::Internal::Type::BaseModel
      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_reader folder_no: String?

      def folder_no=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader total_items: Integer?

      def total_items=: (Integer) -> Integer

      attr_reader total_size: Integer?

      def total_size=: (Integer) -> Integer

      def initialize: (
        ?created_at: Time,
        ?folder_no: String,
        ?name: String,
        ?total_items: Integer,
        ?total_size: Integer
      ) -> void

      def to_hash: -> {
        created_at: Time,
        folder_no: String,
        name: String,
        total_items: Integer,
        total_size: Integer
      }
    end
  end
end
