module Autorender
  module Models
    type folder_list_params =
      {
        parent_folder_no: String,
        search: String,
        sort: Autorender::Models::FolderListParams::sort
      }
      & Autorender::Internal::Type::request_parameters

    class FolderListParams < Autorender::Internal::Type::BaseModel
      extend Autorender::Internal::Type::RequestParameters::Converter
      include Autorender::Internal::Type::RequestParameters

      attr_reader parent_folder_no: String?

      def parent_folder_no=: (String) -> String

      attr_reader search: String?

      def search=: (String) -> String

      attr_reader sort: Autorender::Models::FolderListParams::sort?

      def sort=: (
        Autorender::Models::FolderListParams::sort
      ) -> Autorender::Models::FolderListParams::sort

      def initialize: (
        ?parent_folder_no: String,
        ?search: String,
        ?sort: Autorender::Models::FolderListParams::sort,
        ?request_options: Autorender::request_opts
      ) -> void

      def to_hash: -> {
        parent_folder_no: String,
        search: String,
        sort: Autorender::Models::FolderListParams::sort,
        request_options: Autorender::RequestOptions
      }

      type sort = :name_asc | :name_desc | :created_at_asc | :created_at_desc

      module Sort
        extend Autorender::Internal::Type::Enum

        NAME_ASC: :name_asc
        NAME_DESC: :name_desc
        CREATED_AT_ASC: :created_at_asc
        CREATED_AT_DESC: :created_at_desc

        def self?.values: -> ::Array[Autorender::Models::FolderListParams::sort]
      end
    end
  end
end
