module Autorender
  module Models
    type folder_delete_response = { message: String }

    class FolderDeleteResponse < Autorender::Internal::Type::BaseModel
      attr_reader message: String?

      def message=: (String) -> String

      def initialize: (?message: String) -> void

      def to_hash: -> { message: String }
    end
  end
end
