module Autorender
  module Models
    type upload_create_from_url_response =
      {
        id: String,
        created_at: Time,
        custom_id: String?,
        extension: String,
        file_no: String,
        folder_no: String?,
        height: Integer?,
        is_duplicate: bool,
        metadata: ::Hash[Symbol, top]?,
        mime_type: String,
        name: String,
        path: String,
        size: Integer,
        tags: ::Array[String],
        thumbnail: String,
        upload_source: String,
        url: String,
        width: Integer?,
        workspace_id: String,
        format_: String,
        hash_: String,
        is_private: bool
      }

    class UploadCreateFromURLResponse < Autorender::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor custom_id: String?

      attr_accessor extension: String

      attr_accessor file_no: String

      attr_accessor folder_no: String?

      attr_accessor height: Integer?

      attr_accessor is_duplicate: bool

      attr_accessor metadata: ::Hash[Symbol, top]?

      attr_accessor mime_type: String

      attr_accessor name: String

      attr_accessor path: String

      attr_accessor size: Integer

      attr_accessor tags: ::Array[String]

      attr_accessor thumbnail: String

      attr_accessor upload_source: String

      attr_accessor url: String

      attr_accessor width: Integer?

      attr_accessor workspace_id: String

      attr_reader format_: String?

      def format_=: (String) -> String

      attr_reader hash_: String?

      def hash_=: (String) -> String

      attr_reader is_private: bool?

      def is_private=: (bool) -> bool

      def initialize: (
        id: String,
        created_at: Time,
        custom_id: String?,
        extension: String,
        file_no: String,
        folder_no: String?,
        height: Integer?,
        is_duplicate: bool,
        metadata: ::Hash[Symbol, top]?,
        mime_type: String,
        name: String,
        path: String,
        size: Integer,
        tags: ::Array[String],
        thumbnail: String,
        upload_source: String,
        url: String,
        width: Integer?,
        workspace_id: String,
        ?format_: String,
        ?hash_: String,
        ?is_private: bool
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        custom_id: String?,
        extension: String,
        file_no: String,
        folder_no: String?,
        height: Integer?,
        is_duplicate: bool,
        metadata: ::Hash[Symbol, top]?,
        mime_type: String,
        name: String,
        path: String,
        size: Integer,
        tags: ::Array[String],
        thumbnail: String,
        upload_source: String,
        url: String,
        width: Integer?,
        workspace_id: String,
        format_: String,
        hash_: String,
        is_private: bool
      }
    end
  end
end
