module Autorender
  module Models
    type upload_generate_token_params =
      {
        file_name: String,
        allow_override: Autorender::UploadGenerateTokenParams::AllowOverride,
        custom_id: String,
        folder: String,
        max_file_size: Integer,
        metadata: ::Hash[Symbol, top],
        random_prefix: bool,
        tags: ::Array[String],
        ttl_seconds: Integer
      }
      & Autorender::Internal::Type::request_parameters

    class UploadGenerateTokenParams < Autorender::Internal::Type::BaseModel
      extend Autorender::Internal::Type::RequestParameters::Converter
      include Autorender::Internal::Type::RequestParameters

      attr_accessor file_name: String

      attr_reader allow_override: Autorender::UploadGenerateTokenParams::AllowOverride?

      def allow_override=: (
        Autorender::UploadGenerateTokenParams::AllowOverride
      ) -> Autorender::UploadGenerateTokenParams::AllowOverride

      attr_reader custom_id: String?

      def custom_id=: (String) -> String

      attr_reader folder: String?

      def folder=: (String) -> String

      attr_reader max_file_size: Integer?

      def max_file_size=: (Integer) -> Integer

      attr_reader metadata: ::Hash[Symbol, top]?

      def metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader random_prefix: bool?

      def random_prefix=: (bool) -> bool

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      attr_reader ttl_seconds: Integer?

      def ttl_seconds=: (Integer) -> Integer

      def initialize: (
        file_name: String,
        ?allow_override: Autorender::UploadGenerateTokenParams::AllowOverride,
        ?custom_id: String,
        ?folder: String,
        ?max_file_size: Integer,
        ?metadata: ::Hash[Symbol, top],
        ?random_prefix: bool,
        ?tags: ::Array[String],
        ?ttl_seconds: Integer,
        ?request_options: Autorender::request_opts
      ) -> void

      def to_hash: -> {
        file_name: String,
        allow_override: Autorender::UploadGenerateTokenParams::AllowOverride,
        custom_id: String,
        folder: String,
        max_file_size: Integer,
        metadata: ::Hash[Symbol, top],
        random_prefix: bool,
        tags: ::Array[String],
        ttl_seconds: Integer,
        request_options: Autorender::RequestOptions
      }

      type allow_override = { folder: bool, tags: bool }

      class AllowOverride < Autorender::Internal::Type::BaseModel
        attr_reader folder: bool?

        def folder=: (bool) -> bool

        attr_reader tags: bool?

        def tags=: (bool) -> bool

        def initialize: (?folder: bool, ?tags: bool) -> void

        def to_hash: -> { folder: bool, tags: bool }
      end
    end
  end
end
