module Autorender
  module Models
    type upload_data =
      {
        id: String,
        file_no: String,
        file_size: Integer,
        format_: String,
        height: Integer?,
        name: String,
        path: String,
        url: String,
        width: Integer?,
        workspace_no: String
      }

    class UploadData < Autorender::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader file_no: String?

      def file_no=: (String) -> String

      attr_reader file_size: Integer?

      def file_size=: (Integer) -> Integer

      attr_reader format_: String?

      def format_=: (String) -> String

      attr_accessor height: Integer?

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader path: String?

      def path=: (String) -> String

      attr_reader url: String?

      def url=: (String) -> String

      attr_accessor width: Integer?

      attr_reader workspace_no: String?

      def workspace_no=: (String) -> String

      def initialize: (
        ?id: String,
        ?file_no: String,
        ?file_size: Integer,
        ?format_: String,
        ?height: Integer?,
        ?name: String,
        ?path: String,
        ?url: String,
        ?width: Integer?,
        ?workspace_no: String
      ) -> void

      def to_hash: -> {
        id: String,
        file_no: String,
        file_size: Integer,
        format_: String,
        height: Integer?,
        name: String,
        path: String,
        url: String,
        width: Integer?,
        workspace_no: String
      }
    end
  end
end
