module Autorender
  module Models
    type upload = { data: Autorender::UploadData, success: bool }

    class Upload < Autorender::Internal::Type::BaseModel
      attr_accessor data: Autorender::UploadData

      attr_accessor success: bool

      def initialize: (data: Autorender::UploadData, success: bool) -> void

      def to_hash: -> { data: Autorender::UploadData, success: bool }
    end
  end
end
