module Autorender
  module Models
    type upload_create_with_token_params =
      { token: String, body: Autorender::Internal::file_input }
      & Autorender::Internal::Type::request_parameters

    class UploadCreateWithTokenParams < Autorender::Internal::Type::BaseModel
      extend Autorender::Internal::Type::RequestParameters::Converter
      include Autorender::Internal::Type::RequestParameters

      attr_accessor token: String

      attr_accessor body: Autorender::Internal::file_input

      def initialize: (
        token: String,
        body: Autorender::Internal::file_input,
        ?request_options: Autorender::request_opts
      ) -> void

      def to_hash: -> {
        token: String,
        body: Autorender::Internal::file_input,
        request_options: Autorender::RequestOptions
      }
    end
  end
end
