module Autorender
  module Models
    type upload_create_from_url_params =
      {
        remote_url: String,
        custom_id: String,
        file_name: String,
        folder: String,
        metadata: String,
        random_prefix: String,
        tags: String,
        transform: String,
        webhook_url: String
      }
      & Autorender::Internal::Type::request_parameters

    class UploadCreateFromURLParams < Autorender::Internal::Type::BaseModel
      extend Autorender::Internal::Type::RequestParameters::Converter
      include Autorender::Internal::Type::RequestParameters

      attr_accessor remote_url: String

      attr_reader custom_id: String?

      def custom_id=: (String) -> String

      attr_reader file_name: String?

      def file_name=: (String) -> String

      attr_reader folder: String?

      def folder=: (String) -> String

      attr_reader metadata: String?

      def metadata=: (String) -> String

      attr_reader random_prefix: String?

      def random_prefix=: (String) -> String

      attr_reader tags: String?

      def tags=: (String) -> String

      attr_reader transform: String?

      def transform=: (String) -> String

      attr_reader webhook_url: String?

      def webhook_url=: (String) -> String

      def initialize: (
        remote_url: String,
        ?custom_id: String,
        ?file_name: String,
        ?folder: String,
        ?metadata: String,
        ?random_prefix: String,
        ?tags: String,
        ?transform: String,
        ?webhook_url: String,
        ?request_options: Autorender::request_opts
      ) -> void

      def to_hash: -> {
        remote_url: String,
        custom_id: String,
        file_name: String,
        folder: String,
        metadata: String,
        random_prefix: String,
        tags: String,
        transform: String,
        webhook_url: String,
        request_options: Autorender::RequestOptions
      }
    end
  end
end
