module Autorender
  module Resources
    class Files
      def retrieve: (
        String file_no,
        ?request_options: Autorender::request_opts
      ) -> Autorender::Models::FileRetrieveResponse

      def list: (
        ?folder_no: String,
        ?limit: Integer,
        ?name: String,
        ?page: Integer,
        ?path: String,
        ?sort: Autorender::Models::FileListParams::sort,
        ?tags: String,
        ?request_options: Autorender::request_opts
      ) -> Autorender::Models::FileListResponse

      def delete: (
        String file_no,
        ?request_options: Autorender::request_opts
      ) -> nil

      def rename: (
        String file_no,
        name: String,
        ?request_options: Autorender::request_opts
      ) -> Autorender::Models::FileRenameResponse

      def initialize: (client: Autorender::Client) -> void
    end
  end
end
