module Autorender
  module Resources
    class Folders
      def create: (
        name: String,
        ?parent_folder_no: String,
        ?request_options: Autorender::request_opts
      ) -> Autorender::Models::FolderCreateResponse

      def list: (
        ?parent_folder_no: String,
        ?search: String,
        ?sort: Autorender::Models::FolderListParams::sort,
        ?request_options: Autorender::request_opts
      ) -> Autorender::Models::FolderListResponse

      def delete: (
        String folder_no,
        ?request_options: Autorender::request_opts
      ) -> nil

      def rename: (
        String folder_no,
        name: String,
        ?request_options: Autorender::request_opts
      ) -> Autorender::Models::FolderRenameResponse

      def initialize: (client: Autorender::Client) -> void
    end
  end
end
