module Autorender
  module Resources
    class Uploads
      def create: (
        file: Autorender::Internal::file_input,
        file_name: String,
        ?custom_id: String,
        ?folder: String,
        ?metadata: String,
        ?random_prefix: String,
        ?tags: String,
        ?transform: String,
        ?request_options: Autorender::request_opts
      ) -> Autorender::Upload

      def initialize: (client: Autorender::Client) -> void
    end
  end
end
