module Autorender
  module Models
    module Uploads
      type multipart_complete_params =
        { session_id: String } & Autorender::Internal::Type::request_parameters

      class MultipartCompleteParams < Autorender::Internal::Type::BaseModel
        extend Autorender::Internal::Type::RequestParameters::Converter
        include Autorender::Internal::Type::RequestParameters

        attr_accessor session_id: String

        def initialize: (
          session_id: String,
          ?request_options: Autorender::request_opts
        ) -> void

        def to_hash: -> {
          session_id: String,
          request_options: Autorender::RequestOptions
        }
      end
    end
  end
end
