module Autorender
  class FileDeleteParams = Autorender::Models::FileDeleteParams

  class FileListParams = Autorender::Models::FileListParams

  class FileRenameParams = Autorender::Models::FileRenameParams

  class FileRetrieveParams = Autorender::Models::FileRetrieveParams

  class FileUpdateParams = Autorender::Models::FileUpdateParams

  class FolderCreateParams = Autorender::Models::FolderCreateParams

  class FolderDeleteParams = Autorender::Models::FolderDeleteParams

  class FolderRenameParams = Autorender::Models::FolderRenameParams

  class UploadCreateFromURLParams = Autorender::Models::UploadCreateFromURLParams

  class UploadCreateParams = Autorender::Models::UploadCreateParams

  class UploadGenerateTokenParams = Autorender::Models::UploadGenerateTokenParams

  class UploadUploadWithTokenParams = Autorender::Models::UploadUploadWithTokenParams
end
