module Autorender
  class FileDeleteParams = Autorender::Models::FileDeleteParams

  class FileListParams = Autorender::Models::FileListParams

  class FileRenameParams = Autorender::Models::FileRenameParams

  class FileRetrieveParams = Autorender::Models::FileRetrieveParams

  class FolderCreateParams = Autorender::Models::FolderCreateParams

  class FolderDeleteParams = Autorender::Models::FolderDeleteParams

  class FolderListParams = Autorender::Models::FolderListParams

  class FolderRenameParams = Autorender::Models::FolderRenameParams

  class MultipartUploadCompleteParams = Autorender::Models::MultipartUploadCompleteParams

  class MultipartUploadStartParams = Autorender::Models::MultipartUploadStartParams

  class UploadCreateFromURLParams = Autorender::Models::UploadCreateFromURLParams

  class UploadCreateParams = Autorender::Models::UploadCreateParams
end
