module Autorender
  class FileDeleteParams = Autorender::Models::FileDeleteParams

  class FileListItem = Autorender::Models::FileListItem

  class FileListParams = Autorender::Models::FileListParams

  class FileObject = Autorender::Models::FileObject

  class FileRenameParams = Autorender::Models::FileRenameParams

  class FileRetrieveParams = Autorender::Models::FileRetrieveParams

  class FileUpdateParams = Autorender::Models::FileUpdateParams

  class Folder = Autorender::Models::Folder

  class FolderCreateParams = Autorender::Models::FolderCreateParams

  class FolderDeleteParams = Autorender::Models::FolderDeleteParams

  class FolderListItem = Autorender::Models::FolderListItem

  class FolderListParams = Autorender::Models::FolderListParams

  class FolderRenameParams = Autorender::Models::FolderRenameParams

  class Upload = Autorender::Models::Upload

  class UploadCreateFromURLParams = Autorender::Models::UploadCreateFromURLParams

  class UploadCreateParams = Autorender::Models::UploadCreateParams

  class UploadCreateWithTokenParams = Autorender::Models::UploadCreateWithTokenParams

  class UploadData = Autorender::Models::UploadData

  class UploadGenerateTokenParams = Autorender::Models::UploadGenerateTokenParams

  module Uploads = Autorender::Models::Uploads
end
